### ISSUE TITLE
ICPSR vs Persons

### ISSUE THREAD

**Issue by adamboche** [voteview/WebVoteView#116]
We decided to use the two-collections scheme (members and rollcalls) for a couple behind-the-scenes reasons, but I wonder if you guys think it may still be interesting to have information on humans. For example, searching _Arlen Specter_, who changed from Republican to Democrat, gives two members: 
![image](https://cloud.githubusercontent.com/assets/19828875/21943411/fd3d30a2-d985-11e6-975a-0cf34475afd3.png)
and each one's page excludes data from the other. This may be the behavior we want, since these are the entities that are issued nominate scores. On the other hand, if a user is interested in the legislative behavior of Arlen Specter, they may not be expecting him to be treated as two different people. 

One approach could be linking from each member's page to that human's other pages. I'm not sure what the best strategy is, but I think this is an issue we should tackle in some way. 

At the moment, there is a `person_id` field for each member, which indexes human beings, such that all the Arlen Specter members have the same `person_id`, while having either one of two different `icpsr` values. What do you guys think?

**Comment by aaronrudkin** [comment]
Yeah it would be very easy for me to switch this and I don't have a strong preference. If you do go to Arlen Specter, I believe it will say "Served Previous as a Republican" or "Served Subsequently as a Democrat" and link you to the relevant version. So if it's just a question of the search results, I'm fine either way and would be happy to switch if you all prefer it to be a 1-per-human thing.

**Comment by adamboche** [comment]
I'm not certain about what to do here either. Should all his person-members
appear in his previous-congresses dropdown menu?

**Comment by aaronrudkin** [comment]
I made two fixes to this:

1. Searches now only return one result per person. How this gets canonicalized should generally be their first party but the stage where I do the check is such that there may be some other cases.
2. Bio pages now have a better (faster, cleaner, more reliable) method of checking for previous/subsequent service. The old method involved trying to do name and partial ICPSR matches, which clearly is not what we want.
