### ISSUE TITLE
Renaming tabs?

### ISSUE THREAD

**Issue by JeffreyBLewis** [voteview/WebVoteView#127]
I think we should change the tabs at the top of the page from:
   search / your district / parties / legislators / votes / blog / data / about
to

Option 1: 
   search / geography / party / chamber / summary / blog / data / about
and then maybe reorder
   search / chamber / party / geography / summary / blog / data / about

Option 2: 
   votes / chambers / parties / geographies / summary / blog / data / about

**Comment by adamboche** [comment]
Sounds good. I implemented Option 1. @JeffreyBLewis How's that?

**Comment by lukesonnet** [comment]
I kind of liked it before. Seemed more obvious to users. I'm mostly talking
about the 'geography' tab.

Luke Sonnet
PhD Student, Political Science
UCLA

**Comment by JeffreyBLewis** [comment]
Maybe.  'Your district'  doesn't really seem to capture it either.   Geography also seems like more of a parallel category to the others.

**Comment by lukesonnet** [comment]
Fair enough. I'd just as soon nix/bury summary altogether to increase the
probability of clicks to cool stuff.

Luke Sonnet
PhD Student, Political Science
UCLA

**Comment by JeffreyBLewis** [comment]
Agreed.  That tab could be great, but at the moment isn't.  I would be
happy to drop it for now.   Coming up with to drop list of good summaries
would be a great target for future development.

>
>

-- 

Jeffrey B. Lewis
Professor and Chair
Department of Political Science
University of California, Los Angeles
BOX 951472, 4289A Bunche Hall
Los Angeles, CA 90095-1472

President
The Society for Political Methodology

**Comment by aaronrudkin** [comment]
I don't think chamber, party, or geography are great labels. I agree we should orphan the summary page right now or at least take it off the top tier navigation.

**Comment by lukesonnet** [comment]
I vote for, perhaps misleadingly but I think people would figure it out:

Members, Parties, Districts

I think it is clear, it gets you to where you need to be. I agree geography is more parallel, Jeff, but it is a bit misleading!

**Comment by lukesonnet** [comment]
Can we close this or should I implement my suggestion. All I need is one vote and I'll pull the trigger (sick voting rule huh) either way.
