### ISSUE TITLE
Missing Cutline tooltip

### ISSUE THREAD

**Issue by lukesonnet** [voteview/WebVoteView#146]
We should display some kind of tooltip if the cutline/shading are missing from the ellipse. If there is no shading on the ellipses, then two conditions are possible (barring a total disaster):

1. There is no PRE computed. Either this means that either nominate or no PRE at all. Given no rollcall should be missing nominate data I would suggest saying to the user "Nominate data has not yet been computed for this rollcall" or something like that.

2. There is a PRE but it is < 0.05. This means the vote is not "ideological" in two dimensions and just guessing the majority vote for any individual will yield similar if not better results than any line in the space. We should display something like "This vote is not sufficiently ideological in two dimensions, and thus we do not display a cut line".

**Comment by JeffreyBLewis** [comment]
Talked about this with the rest of the team yesterday.  We will replace the classified/pre box with an explanation as suggested.   Should also shade the oval uniformly reflecting the prob yea. 

Now that we have the heatmap. I wonder if we should relax the pre>0.05 threshold.    It seems like we could still show the cut lines in these cases.  Where we might suppress this are the so called constrained votes where the cut line is tangent to the bounding ellipse.  And also on the lopsided votes where nominate wasn't fit.

**Comment by aaronrudkin** [comment]
I now display the text "Non-Ideological Vote" when PRE<0.05, and "NOMINATE not yet computed" when PRE or nominate is absent altogether. We can do an explainer below the oval if you'd prefer or in addition to this behaviour.
