### ISSUE TITLE
Notes from Howard Rosenthal

### ISSUE THREAD

**Issue by JeffreyBLewis** [voteview/WebVoteView#150]
I got the attached from HR.  Some easy and fast others less so, all good ideas.  I will try to the "about" part today.   Let's see if we can get the bill/amendment sponsor into the data onto the vote page ASAP.   Ideally, it would great if we could also highlight the sponsor in the ellipse and in the member list, but obviously that requires some real work to match the "sponsor" text up with a member in the DB.

[Comments on UCLA Voteview.docx](https://github.com/JeffreyBLewis/WebVoteView/files/732808/Comments.on.UCLA.Voteview.docx)

**Comment by aaronrudkin** [comment]
Jeff if you've taken the About page that's good.

**Stuff that is either done or in another active issue** 
RE: "Dates active" -- the dates active are incorrect in a predictable way right now, explained in #79 
RE: Reason for no cutline, this was fixed last night in #146 
RE: Cross-tabs, they can go in #38. 

**Stuff that I will do and we can keep in this issue**
RE: New member DW-NOM; I can add career number of votes, we have the info, but not sure if we prefer this or just a binary yes/no explainer for people with number of votes below a threshold
RE: Legend; I can add a tooltip for Classified/PRE, this will also allow additional explaining for the reason for no cutline.

**Stuff to open individual issues for**
I will open an issue for proposers/sponsors. 

I will open an issue for votes that have so many parties the party vote list has spillover -- basically we should at least check a representative vote every congress. I thought the minor party combining trick was enough to mitigate this, but the 48th has 4 real parties and that vote exhibits Yea, Nay, and Abs for each of 3 and Abs for one. D'oh.

**Comment by aaronrudkin** [comment]
I have text added for people with no nominate score or a low number of votes on their vote pages.

NOMINATE score but not many votes (note, there's a visual glitch on load here, I am aware):
http://128.97.229.160/person/41700/catherine-marie-cortez-masto

No NOMINATE score:
http://128.97.229.160/person/8449/upton-sheredine

No NOMINATE score, special case, President:
http://128.97.229.160/person/99869/george-washington

Please please please please please correct my boilerplate explainer text to make it accurate.

**Comment by JeffreyBLewis** [comment]
I have edited the "about" page per HR.  I didn't go exactly with what was requested.  I put the some of gnarly details into note that are applied as tooltip to the "Voteview for DOS" and "Voteview for Windows".  There is probably a better way to indicate the presence of the note.

I have also taken a more expansive approach to the lopsided votes.  Now:

(1) Show all estimated cutlines/heatmaps regardless of fit (PRE) 
(2) Lopsided votes get a uniform heatmap and tooltip
(3) The text in the class box reads "Lopsided without ideological division" on votes without cutlines

I think this gives a much more consistent and expected display across votes.

Those changes are on dev and are ready to be deployed.

**Comment by JeffreyBLewis** [comment]
I think we should give some base-card like summary stats on the member pages to highlight the instability issues.  However, that is on the issue with Cruz v. Cassidy yea probabilities that HR points out  Cassidy is positioned much more centrally that Cruz. However, the probability gradient is not monotonic in distance from the cutline so in fact centrist Cassidy closer to the cut line has (trivially) lower Pr(Y) than Cruz.   

The positions should stabilize pretty quickly, sort of root n thing.  So you should probably be pretty stable after say 100 or 200 votes (putting aside agenda affects).

**Comment by JeffreyBLewis** [comment]
@aaronrudkin 's call for not-enough-votes for nominate or reliable nominate score are great, but need specify the specific number of votes for the no score calculated case.

**Comment by lukesonnet** [comment]
Why does it say that http://128.97.229.160/person/29346/bobby-l-rush has too few votes? I doubt that is true.

**Comment by aaronrudkin** [comment]
Posting to let Adam and Jeff in on the conclusion here: @lukesonnet and I discussed this earlier--currently the vote numbers are per-congress and it's not easy for me to aggregate across all congresses. Luke or Adam need to make a field called nominate.total_number_of_votes that aggregates across congresses and put it into the ingestion process, then that will fix.
