### ISSUE TITLE
Create stub for Donald J. Trump

### ISSUE THREAD

**Issue by aaronrudkin** [voteview/WebVoteView#159]
Currently, we don't have any voting data for President Trump, because we rely on CQ or whomever to provide it. That's fine, but I think we should make a stub so that if anyone searches they find him. I wrote a bio and got his presidential portrait of choice, so it's just a matter of adding the stub. (ICPSR 99912)

This should be done either in a reusable query or in code so that it can be baked into the ingestion process.

**Comment by adamboche** [comment]
Sounds good. If you post it here and tag me ill put it into the ingestion.

**Comment by aaronrudkin** [comment]
I'm not sure how you do the ICPSR generation and the initial onboarding of a member. His bio is in the president bio import that's already in ingestion and his photo is in the folder--so from that point of view it's done.

It's something like this (filling out all the rest should be later in the ingestion step)
`db.voteview_members.insert({"icpsr": 99912, "id": "MP11599912", "congress": 115, "district_code": 0,
"name": "TRUMP", "chamber": "President", "party_code": 200, "fname": "TRUMP, DONALD", "bioname": "TRUMP, Donald J.", "state_abbrev": "USA", "born": 1946, "died": null, "twitter": "POTUS", "last_means": 0, "occupancy": 0, "state_name": "PRESIDENT", "state_fips": "", "state_icpsr": 99, "vns_ID": ""})`

But since I don't know how you actually allocate new ICPSRs I wouldn't want to do this and then have him get a separate ICPSR when we do get data.

**Comment by aaronrudkin** [comment]
@adamboche This should still happen, even if we don't have vote data.

**Comment by aaronrudkin** [comment]
@adamboche Not that this is the world's most important thing to do, but we should probably do this even if we no longer have a source to score the president. Is there a particular script I can insert the above query into to make this happen?

**Comment by adamboche** [comment]
I think you can just do it raw. I don't remember if anything bad happens if we have members who never voted, but if it breaks we can just delete him and deal with it later.

**Comment by aaronrudkin** [comment]
This is done. The final query also has a stub biography written in Cong. Bioguide style (I also did these for the previous presidents who didn't serve in congress like GWB, Clinton, Reagan, etc.) -- there are few broken things on the bio page since he has no votes at all but I'll open a separate issue for that. This may take a little while to propagate to the main server.

**Comment by aaronrudkin** [comment]
Ah, yes, sorry about that!
