### ISSUE TITLE
Search suggestions too attention-grabby

### ISSUE THREAD

**Issue by adamboche** [voteview/WebVoteView#184]
Howard:  

> "Suggestions"  pop up in the search bar.  I find this distracting.

Jeff: 

>  I think it is helpful for folks to get a sense of what they might put in search box, but perhaps that should go away after a few seconds or if the mouse is moved towards the search box or something.

Maybe they could fade or something.

Also, "enter a term to search for" seems unnecessary

**Comment by lukesonnet** [comment]
Do we not like my suggestion?

> I agree about suggestions, maybe they could pop up below the search bar, or just have two or three with varying syntax in small font below the search bar that are clickable.
> 
> Suggested searches: affordable care act, iraq war congress:102, orrin hatch

**Comment by aaronrudkin** [comment]
Yeah, they could easily be put below the search bar and clickable, and that would actually help with some of the previous issues we had with the focus being unclear.

**Comment by lukesonnet** [comment]
I swear to god the focus just started happening again this week when I click 'back' to the main page. I never can replicate it intentionally but it keeps happening.

**Comment by aaronrudkin** [comment]
Okay I am going to put the search suggestions as text links below the bar. I will not be getting rid of "enter a term to search for" unless people have a strong preference, because users are not great at knowing what they can search for until they've tried things a few times.

**Comment by aaronrudkin** [comment]
This is done.
