### ISSUE TITLE
Search 

### ISSUE THREAD

**Issue by adamboche** [voteview/WebVoteView#199]
From Howard:

> Also, I continue to find the Search confusing.  It returns 0 roll calls at times unless I exit the tab and start over.  Maybe a "reset" search" button.  Eventually I get it to find what I want, but I am not sure what I do wrong when it does not work.

**Comment by aaronrudkin** [comment]
I suspect the issue here is that he does a search, then uses the filters to narrow down to some specific subset, then updates the text search without the filters being cleared. Does anyone else think this is the most likely explanation?
