### ISSUE TITLE
Remove votes from homepage

### ISSUE THREAD

**Issue by adamboche** [voteview/WebVoteView#231]
> I’d take all of the vote content off of this page and put it on a separate page,
> accessed through the navigation bar as “Votes.”

**Comment by JeffreyBLewis** [comment]
I have asked AP to design a landing page for the site.

**Comment by aaronrudkin** [comment]
Jeff and I talked about this earlier this summer. The plan is to put a large rotating carousel above the vote search, but leave the vote search there. This way there's a good balance between active, engaging content and not burying one of the main features returning users would use. I am going to close the two AP issues discussing this and open a new issue when the carousel is fully implemented so we can discuss content.

**Comment by aaronrudkin** [comment]
The carousel is live on dev. Issues about what to make slides for will be in a different repo.

https://github.com/voteview/slide_carousel/issues
