### ISSUE TITLE
Explain classified/pre

### ISSUE THREAD

**Issue by adamboche** [voteview/WebVoteView#261]
Instead of the tooltips and notes at the bottom right, add a note under the
chart that explains the measures and gives the numbers. Include that in
the image download.

**Comment by aaronrudkin** [comment]
This is sort of done. I took PRE/Classified off the main canvas and put them under the x-axis labels, which created enough horizontal space to provide fuller descriptions of these terms. I don't have a whole paragraph explainer. I don't think this is necessarily the complete answer here, but it does improve how we present the NOMINATE oval.
