### ISSUE TITLE
Vote table ideology

### ISSUE THREAD

**Issue by adamboche** [voteview/WebVoteView#268]
If sorting by ideology, show the NOMINATE number not just on
rollover.

**Comment by aaronrudkin** [comment]
I'm going to push back against this one on two bases:

1. Conceptually, I think there is an advantage to bury the NOMINATE scores a bit. The people who want to work with the data can know the exact numbers, but in general I don't think the public wants to (nor do we want people reading things into the numbers not justified by the model). Of course I think the data should be available for those who want it, but I kinda like the compromise we have now, which is that until a user interacts with the data we're not revealing it.

2. That being said, I did experiment with trying to fit the numbers in the table and it doesn't really work visually. It's easy to fit the number, but not easy to fit the number and a tag like NOMINATE or Ideology that describes that the number in brackets is. Short of throwing out the columnar interface and having a long tabular interface (which loses the ability to e.g. see the entire Senate on a single page on a standard monitor), I don't think there's an obvious way to show this.

If there is not a strong preference for trying to make this work, I am going to close without action here.
