### ISSUE TITLE
Vote prob

### ISSUE THREAD

**Issue by adamboche** [voteview/WebVoteView#269]
I like the concept of showing unlikely votes, but it might
need some clarification. Try sorting by vote first and then
sorting by predicted probability of vote. Add a key
indicating that the red is for probabilities of 25% or less.
![image](https://cloud.githubusercontent.com/assets/19828875/26524954/ecab0752-42fb-11e7-93ee-85e34af4c714.png)

**Comment by aaronrudkin** [comment]
This is done.
