### ISSUE TITLE
Party chart

### ISSUE THREAD

**Issue by adamboche** [voteview/WebVoteView#276]
Instead of a paragraph explaining how to read the chart, add a headline
(Ideologies of major parties in Congress) and a shorter piece of summary
text. Label More liberal v​ More conservative ^​ and the party names
directly on the chart and add a simple key:
● [dots] the range of ideologies within a party
● [lines] median ideology within a party
● [grey line] median across all parties ← could even put this label
directly on the chart

**Comment by aaronrudkin** [comment]
This is done, except for the party names, which I think would get pretty cluttered pretty fast:

https://vanguard.voteview.com/parties/all
