### ISSUE TITLE
Geography examples

### ISSUE THREAD

**Issue by adamboche** [voteview/WebVoteView#280]
I like that you have examples already in there. Could start with one clicked on so
when you get to the page you can see what things look like when there’s an
address inputted.

**Comment by aaronrudkin** [comment]
I tried playing around with this and drew two conclusions:

1. The lookup is sufficiently slow (unavoidable, it has to do a pretty complicated geo query across the district data AND rely on Google Maps geocoder lookup, which itself is pretty slow on their end) that this I think makes the entire page experience worse. It's maybe possible to specially cache results of this one query so as to avoid this issue, but that seems like a bit of overhead.

2. My sense is that if the thing automatically runs when you load the page, most users will be confused into believing geolocation is occurring and incorrectly believing the site thinks they're located in the automatic lookup.
