### ISSUE TITLE
Credentials for www

### ISSUE THREAD

**Issue by adamboche** [voteview/WebVoteView#316]
When I go to www.voteview.com (with the www), Chrome tells me:

> www.voteview.com normally uses encryption to protect your information. When Google Chrome tried to connect to www.voteview.com this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be www.voteview.com, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Google Chrome stopped the connection before any data was exchanged.
You cannot visit www.voteview.com right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later. Learn more.

**Comment by aaronrudkin** [comment]
Done.
