### ISSUE TITLE
How is party loyalty calculated?

### ISSUE THREAD

**Issue by adamboche** [voteview/WebVoteView#347]
![image](https://user-images.githubusercontent.com/19828875/44554008-3b278480-a6e4-11e8-83c1-a7a4190fd73c.png)
http://128.97.229.160/person/41304/rafael-edward-ted-cruz

How is the 95% calculated? Is it just (number of votes cast agreeing with own party's majority position) / (number of votes cast)?

Can we document these calculations somewhere, or make them hover-text or something?

**Comment by aaronrudkin** [comment]
Luke wrote this code originally. I do plan on going through it, rewriting the code to clean it up a little bit, and then documenting it. Thanks for the reminder. It's currently documented in voteview_metadata/updateDB/memberEdits/add_party_loaylty.py

**Comment by adamboche** [comment]
@lukesonnet Can you confirm it's the member's number of votes with their party's majority position / member's number of votes total?

**Comment by adamboche** [comment]
Luke confirms: That's correct, with the party majority position. Only clear yeas and nays count in denominator.

**Comment by aaronrudkin** [comment]
Dev is updated to have a tooltip to this effect (I also rewrote how this table was assembled)

https://vanguard.voteview.com/person/40915/joe-manchin-iii
