### ISSUE TITLE
Cross-hatching

### ISSUE THREAD

**Issue by aaronrudkin** [voteview/WebVoteView#348]
As I work my way through finishing up the odds and ends, I've gotten to the vote page. I implemented a mockup of cross-hatching on the vote maps. I was hoping to get some feedback, because my feeling is that it solves the problem it was intended to solve, but creates a new problem, so I wanted to know how you all felt.

By way of background. Before now, senate votes display a colour blend of the colours of the two votes taken by a state's senators. So, for example, Republicans who vote Yea have a saturated red, Republicans who vote Nay have a slightly less saturated red, Republicans who are absent have a very desaturated red. A state with two Republican senators both voting Yea has the full red saturation, a state with two Republican senators who splits has a red between Yea and Nay. A state with a Republican senator who voted Yea and one who was absent has a saturation somewhere near having two senators who voted Nay. Etc.

The problem gets even worse when states have a partisan split, since you get various shades of colours between the existing colour schemes; so over the years there are many different party configurations and many different, annoying shades.

Making matters worse, the blended shades are not visible on the vote table on the right, so you have to mouse over to get any sense of what's going on on the map.

I solved this by making states use cross-hatching to shade the state with the two distinct colours of the votes. This solves all of the above problems and in many cases I don't think looks bad. The one issue I have with it is that in votes that have a lot of geographic splitting, it is a little overwhelming to see all the cross-hatching across the map. So I'm not sure if, all in all, it looks "better" -- it looks more legible but in some cases less pleasant.

Many maps that use cross-hatching will have one "thick" colour and one "thin" colour. We can't do that here, since both senators need to have equal visual weight. I could make the bands themselves thicker or thinner to reduce the "strobe" effect.

Here is an example of a vote:
http://128.97.229.160/rollcall/RS1150516

And without the crosshatching:
http://voteview.com/rollcall/RS1150516

Two final notes:
- If you have difficulty loading the new page, please dump cache and refresh
- For multi-member districts with n_members > 2 in old votes, I just use the blended colour mode. A lot of the multi-member districts have 8-10+ members and there's no plausible way to make use of crosshatching here. But this is a minor edge case.

Any thoughts?

**Comment by adamboche** [comment]
Yes! I think this looks great and is way easier to understand. Thanks for doing this!

**Comment by aaronrudkin** [comment]
Thanks are at least partially due to @matthewseymour who explained the SVG <defs> element to me :+1:
