### ISSUE TITLE
Current mechanism for updating existing member biographies (e.g. after death)

### ISSUE THREAD

**Issue by aaronrudkin** [voteview/WebVoteView#352]
I notice that we still report Louise Slaughter (d. March 16, 2018) and more recently John McCain as still alive.  Can we do some documentation in the Wiki about the correct way to initiate a re-scrape/update of their biographical info from bioguide to reflect deaths? I believe currently we just end up with their bio text being scraped once and then being permanent. I could dump the whole db and rescrape with no difficulty, but surely we have an easier process than this. 

This may also be relevant for updating the bio text to reflect resignations, but I think it's most important that members of congress in the 115th do not appear alive when they are dead

**Comment by adamboche** [comment]
I've updated the wiki with instructions on refreshing members' bio info from the bioguide, and ran it for Slaughter and McCain. Looks like there's a field called `voting_dates` which needs to get updated as well, but I wasn't sure if that happens automatically or if I should add it to this script.

https://github.com/voteview/WebVoteView/wiki/Editing-the-database

**Comment by aaronrudkin** [comment]
🙇 🙇 🙇 🙇 🙇 🙇 👍
