### ISSUE TITLE
On staging, json file download  is a csv

### ISSUE THREAD

**Issue by adamboche** [voteview/WebVoteView#371]
On https://vanguard.voteview.com/data , selecting json members or rollcalls links to a csv file, not a json file.

**Comment by aaronrudkin** [comment]
Can't replicate in Chrome / macOS. What browser / OS are you testing on?

**Comment by adamboche** [comment]
I tried it on some other machines and can't replicate either, so I think this was a browser js configuration thing, not a server-side issue.
