### ISSUE TITLE
District page missing newest rep

### ISSUE THREAD

**Issue by adamboche** [voteview/WebVoteView#380]
- On prod, [WI-01](https://voteview.com/district/1609%20Taylor%20Avenue,%20Racine%20WI%2053403) is represented by [Bryan Steil](https://voteview.com/person/21970/bryan-steil) but he's missing from the district page, which shows Paul Ryan. 
- [On dev](https://vanguard.voteview.com/district/1609%20Taylor%20Avenue,%20Racine%20WI%2053403) he's there, but his photo is missing.

@aaronrudkin Do you know what's going on with these?

**Comment by aaronrudkin** [comment]
Jeff and I have fixed the districts (fixes propagating now). Basically the district database wasn't updated with new districts for the 116th. The photo issue is unusual, but I think we can open a separate issue about this if it's not as simple as just "freshman photo wasn't found for a while"
