### ISSUE TITLE
LImits to results of searches for members by name

### ISSUE THREAD

**Issue by JeffreyBLewis** [voteview/WebVoteView#385]
It appears that when member names are searched for the number of returns is limited (perhaps to 8?).  Here is an example,

<img width="1125" alt="Screen Shot 2019-11-15 at 10 34 29 AM" src="https://user-images.githubusercontent.com/4761445/68966884-f6c64f80-0793-11ea-98c4-512de3ba10ed.png">

You can see that John F. Kennedy is not included among the returns though he has a record in the database.

**Comment by aaronrudkin** [comment]
This is fixed in python3.
