### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by fasouto** [voteview/WebVoteView#42]
If you want to release this software it may be a good idea to include a LICENSE file

**Comment by aaronrudkin** [comment]
We followed up with this in a meeting yesterday. Apparently we have to check with UCLA legal counsel about what licenses are an option. I will update/close this issue and add a license file when we have an answer.

**Comment by adamboche** [comment]
@JeffreyBLewis Reminder

**Comment by JeffreyBLewis** [comment]
Left message with university folks that do this sort of thing yesterday.  No response as yet.

**Comment by aaronrudkin** [comment]
JBL got word back from the appropriate legal people -- we're MIT licensed. Glad we finally have clarity on this and thanks Fabio for reminding us back in 2016 to get this figured it out.
