### ISSUE TITLE
Wrong image for 19th-century congressman

### ISSUE THREAD

**Issue by surf-solar** [voteview/WebVoteView#423]
https://voteview.com/person/2867/john-edwards

The John Edwards linked to above is a one-term congressman from New York in the 25th congress (1837-39), but the image shown is of the North Carolina senator from the 1990s/2000s of the same name.

**Comment by JeffreyBLewis** [comment]
Thank you @surf-solar for pointing this out.  I have removed the incorrect photo.  At the moment, we do not have an image for the correct John Edwards of New York.
