### ISSUE TITLE
Building out data features

### ISSUE THREAD

**Issue by lukesonnet** [voteview/WebVoteView#68]
As far as I am concerned, the data page provide the service that it needs to. The biggest work that needs to happen is documentation, but that is a site-wide problem and not a data specific problem.

This issue is to discuss how we will handle versioning, providing stable releases for research purposes, and the possibility of an Rmd gallery for student plots and analyses that come out of our data. I'll drop some ideas/commits here in the coming weeks.

Also, drop any design recommendations or meta data type stuff that should go here.

**Comment by aaronrudkin** [comment]
Hey. I've been looking at the data page a bit and I feel like while the core functionality is there, it's completely incomprehensible to someone that doesn't know what they're looking for. Maybe I'm underestimating the journalist / interested lay-person nerd audience, but I had to sit back and figure out what I actually wanted. Is there any way you could put small descriptions below each header or rename the headers?

Something like this:
Rollcall parameters and metadata -> "Information about congressional rollcall votes (.CSV)"
Member ideal points and metadata -> "Information about member ideology (.CSV)"
Party ideology and metadata -> This one is fine, but add (.CSV) to the end.

(make everything starting here a smaller font size)
Roll call data -> Legacy Voteview File Formats 
Headers under it should be by file format, like:
Legacy Rollcall Matrices (.ORD files)
Legacy Rollcall Flatfiles (.DAT files)
Legacy Member Flatfiles (.DAT files)
Extra Legacy Information -> Clausen, Peltzman, and Issue codes for 1st to 113th Congresses

This is not going to be less comprehensible to political scientists, but it will be more comprehensible to our broader audience, right?

Also maybe a paragraph after the header "Realtime NOMINATE and Related Data" and before any of the data just explaining what our options are, and how if you need help determining how to use our data, contact us (link to about page, etc.)?

**Comment by lukesonnet** [comment]
Yes I can build this out.

Luke Sonnet
PhD Student, Political Science
UCLA

**Comment by lukesonnet** [comment]
Good suggestion. Looks much better now. Next step is docs that @adamboche and I have to work on.

**Comment by aaronrudkin** [comment]
Luke, this is very good work. This looks much better. Thank you.

**Comment by lukesonnet** [comment]
It seems like we have no versioning in place, I still think it should archive the csvs and vote matrices at the end of each session.

Also want to know if we still have any interest on having those data analysis pages somewhere.

**Comment by aaronrudkin** [comment]
This has been resolved in several ways:

1. The data page has been rewritten to link to help files for each data thing
2. Data analysis pages now exist through the articles system.
